### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mikehale** [asenchi/scrolls#68]
Any chance we can get a 0.3.9 published or at least a 0.3.9.pre pushed to rubygems?

**Comment by asenchi** [comment]
I know I'm answering this two years too late, but 0.3.9 is out. 0.9.0 is soon to be released which will be a major refactor (see #71 and #54) to support recent changes in Ruby versions. 0.9.0 has breaking changes, which is why I bumped the version really far. I'd also like to drive Scrolls itself to a 1.0, but that will require some work on the unparse/parser setup to support most of these issues (https://github.com/asenchi/scrolls/issues?q=is%3Aissue+is%3Aopen+label%3Aparser-work).

That is if anyone uses Scrolls anymore after years of neglect on my behalf. Expect a 0.9.0 within the next week or so.

**Comment by gorsuch** [comment]
lol (and heck yeah)
